Repository Betarena/scores, pull requests merged in 2021-12, with the labels that each got.

#42 Feature/cross platform header dynamix lang change
  src/lib/components/header/Header.svelte
  src/lib/model/scores_header_translations.ts
  static/assets/svg/sport-icon/american football.svg
  static/assets/svg/sport-icon/aussie rules.svg
  static/assets/svg/sport-icon/badminton.svg
  static/assets/svg/sport-icon/bandy.svg
  static/assets/svg/sport-icon/baseball.svg
  static/assets/svg/sport-icon/basketball.svg
  static/assets/svg/sport-icon/beach volleyball.svg
  static/assets/svg/sport-icon/boxing.svg
  static/assets/svg/sport-icon/cricket.svg
  static/assets/svg/sport-icon/darts.svg
  static/assets/svg/sport-icon/esports.svg
  static/assets/svg/sport-icon/floorball.svg
  static/assets/svg/sport-icon/football.svg
  static/assets/svg/sport-icon/futsal.svg
  static/assets/svg/sport-icon/handball.svg
  static/assets/svg/sport-icon/ice hockey.svg
  static/assets/svg/sport-icon/mma.svg
  static/assets/svg/sport-icon/motorsport.svg
  static/assets/svg/sport-icon/rugby.svg
  static/assets/svg/sport-icon/snooker.svg
  static/assets/svg/sport-icon/table tennis.svg
  static/assets/svg/sport-icon/tennis.svg
  static/assets/svg/sport-icon/volleyball.svg
  static/assets/svg/sport-icon/waterpolo.svg
Labels: bug, enhancement

#43 Dev
  README.md
  package-lock.json
  package.json
  src/app.css
  src/lib/components/footer/Footer.svelte
  src/lib/components/footer/assets/betarena-logo-full.svg
  src/lib/components/header/Header.svelte
  src/lib/components/header/assets/arrow-down-fade.svg
  src/lib/components/header/assets/arrow-down.svg
  src/lib/components/header/assets/arrow-up-fade.svg
  src/lib/components/header/assets/arrow-up.svg
  src/lib/components/header/assets/betarena-logo-full.svg
  src/lib/components/header/assets/betarena-logo-mobile.svg
  src/lib/components/header/assets/close.svg
  src/lib/components/header/assets/menu-burger.svg
  src/lib/components/header/assets/menu_sports_icon.svg
  src/lib/components/header/assets/sports-icons/archery.svg
  src/lib/components/header/assets/sports-icons/baseball.svg
  src/lib/components/header/assets/sports-icons/basketball.svg
  src/lib/components/header/assets/sports-icons/bowling.svg
  src/lib/components/header/assets/sports-icons/soccer.svg
  src/lib/components/header/assets/sports-icons/tennis.svg
  src/lib/components/header/assets/sports-icons/volleyball.svg
  src/lib/components/header/assets/theme-light-icon.svg
  src/lib/graphql/init_graphQL.ts
  src/lib/graphql/query.ts
  src/lib/header/Header.svelte
  src/lib/model/scores_header_translations.ts
  src/lib/store/lang-select.ts
  src/routes/[lang].svelte
  src/routes/__layout.svelte
  src/routes/index.svelte
  static/assets/svg/sport-icon/american football.svg
  static/assets/svg/sport-icon/aussie rules.svg
  static/assets/svg/sport-icon/badminton.svg
  static/assets/svg/sport-icon/bandy.svg
  static/assets/svg/sport-icon/baseball.svg
  static/assets/svg/sport-icon/basketball.svg
  static/assets/svg/sport-icon/beach volleyball.svg
  static/assets/svg/sport-icon/boxing.svg
  static/assets/svg/sport-icon/cricket.svg
  static/assets/svg/sport-icon/darts.svg
  static/assets/svg/sport-icon/esports.svg
  static/assets/svg/sport-icon/floorball.svg
  static/assets/svg/sport-icon/football.svg
  static/assets/svg/sport-icon/futsal.svg
  static/assets/svg/sport-icon/handball.svg
  static/assets/svg/sport-icon/ice hockey.svg
  static/assets/svg/sport-icon/mma.svg
  static/assets/svg/sport-icon/motorsport.svg
  static/assets/svg/sport-icon/rugby.svg
  static/assets/svg/sport-icon/snooker.svg
  static/assets/svg/sport-icon/table tennis.svg
  static/assets/svg/sport-icon/tennis.svg
  static/assets/svg/sport-icon/volleyball.svg
  static/assets/svg/sport-icon/waterpolo.svg
  svelte.config.js
Labels: bug, enhancement

#48 Feature/cross platform header dynamix lang change
  src/lib/components/header/Header.svelte
  src/lib/graphql/query.ts
  src/lib/model/scores_header_translations.ts
  src/routes/[lang].svelte
Labels: bug, enhancement

#49 Feature/cross platform header dynamix lang change (#48)
  src/lib/components/header/Header.svelte
  src/lib/graphql/query.ts
  src/lib/model/scores_header_translations.ts
  src/routes/[lang].svelte
Labels: bug, enhancement

#52 adding PWA support to the sveltekit application
  src/app.html
  src/lib/components/Offline_alert.svelte
  src/routes/__layout.svelte
  src/service-worker.ts
  static/assets/img/192x192.png
  static/assets/img/512x512.png
  static/manifest.json
Labels: enhancement

#55 Feature/pwa
  src/app.html
  src/lib/components/Splash_screen.svelte
  src/routes/__layout.svelte
  static/assets/img/pwa/114x114 (iOS).png
  static/assets/img/pwa/120x120 (iOS).png
  static/assets/img/pwa/152x152 (iOS).png
  static/assets/img/pwa/180x180 (iOS).png
  static/assets/img/pwa/57x57 (iOS).png
  static/assets/img/pwa/60x60 (iOS).png
  static/assets/img/pwa/72x72 (iOS).png
  static/assets/img/pwa/76x76 (iOS).png
  static/manifest.json
Labels: enhancement

#56 Feature/pwa
  src/lib/components/Splash_screen.svelte
  static/assets/svg/logo-main.svg
  static/manifest.json
Labels: bug, enhancement

#51 Feature/cross platform header dynamix lang change (#50) + PWA
  src/app.html
  src/lib/components/Offline_alert.svelte
  src/lib/components/Splash_screen.svelte
  src/lib/components/header/Header.svelte
  src/lib/graphql/query.ts
  src/lib/model/scores_header_translations.ts
  src/routes/__layout.svelte
  src/service-worker.ts
  static/assets/img/192x192.png
  static/assets/img/512x512.png
  static/assets/img/pwa/114x114 (iOS).png
  static/assets/img/pwa/120x120 (iOS).png
  static/assets/img/pwa/152x152 (iOS).png
  static/assets/img/pwa/180x180 (iOS).png
  static/assets/img/pwa/57x57 (iOS).png
  static/assets/img/pwa/60x60 (iOS).png
  static/assets/img/pwa/72x72 (iOS).png
  static/assets/img/pwa/76x76 (iOS).png
  static/assets/svg/logo-main.svg
  static/manifest.json
Labels: enhancement

#66 Update robots.txt
  static/robots.txt
Labels: enhancement

#68 Feature/featured match and dark theme and nav change
  Dockerfile
  README.md
  package-lock.json
  package.json
  src/lib/components/featured_match/FeaturedMatch_Widget.svelte
  src/lib/components/featured_match/loaders/desktop/Placeholder_VisualVote.svelte
  src/lib/firebase/index.ts
Labels: enhancement

#69 Feature/featured match and dark theme and nav change
  .github/workflows/docker-image.yml
  Dockerfile
  package-lock.json
  package.json
  src/lib/components/featured_match/FeaturedMatch_Widget.svelte
  src/lib/components/header/Header.svelte
Labels: enhancement

#81 Feature/featured match and dark theme and nav change
  .github/workflows/docker-image.yml
  README.md
  package-lock.json
  package.json
  src/lib/api/utils.ts
  src/lib/components/Splash_screen.svelte
  src/lib/components/featured_match/FeaturedMatch_Widget.svelte
  src/lib/firebase/init.ts
  src/lib/geoJs/init.ts
  src/lib/graphql/init_graphQL.ts
  src/lib/store/user-settings.ts
  src/lib/store/vote_fixture.ts
  src/service-worker.ts
  svelte.config.js
Labels: bug, enhancement

#83 Feature/featured match and dark theme and nav change
  README.md
  WEBSITE-DEV-README.md
  src/app.css
  src/lib/components/featured_match/FeaturedMatch_Widget.svelte
  src/lib/components/header/Header.svelte
  src/lib/geoJs/init.ts
  src/lib/graphql/query.ts
  src/lib/model/response_models.ts
  src/routes/__layout.svelte
Labels: bug, enhancement

#84 Feature/featured match and dark theme and nav change
  src/routes/__layout.svelte
Labels: bug

#87 Feature/featured match and dark theme and nav change
  src/service-worker.ts
Labels: documentation, enhancement

#85 Dev
  .github/workflows/docker-image.yml
  .gitignore
  Dockerfile
  README.md
  WEBSITE-DEV-README.md
  package-lock.json
  package.json
  src/app.css
  src/lib/api/utils.ts
  src/lib/components/Offline_alert.svelte
  src/lib/components/Splash_screen.svelte
  src/lib/components/featured_match/FeaturedMatch_ContentLoading.svelte
  src/lib/components/featured_match/FeaturedMatch_Widget.svelte
  src/lib/components/featured_match/loaders/desktop/Placeholder_BestPlayers.svelte
  src/lib/components/featured_match/loaders/desktop/Placeholder_LeagueInfo.svelte
  src/lib/components/featured_match/loaders/desktop/Placeholder_TvStations.svelte
  src/lib/components/featured_match/loaders/desktop/Placeholder_ValueBets.svelte
  src/lib/components/featured_match/loaders/desktop/Placeholder_VisualVote.svelte
  src/lib/components/featured_match/loaders/mobile/Placeholder_BestPlayers.svelte
  src/lib/components/featured_match/loaders/mobile/Placeholder_LeagueInfo.svelte
  src/lib/components/featured_match/loaders/mobile/Placeholder_TvStations.svelte
  src/lib/components/featured_match/loaders/mobile/Placeholder_ValueBets.svelte
  src/lib/components/featured_match/loaders/mobile/Placeholder_VisualVote.svelte
  src/lib/components/featured_match/loaders/tablet/Placeholder_BestPlayers.svelte
  src/lib/components/featured_match/loaders/tablet/Placeholder_LeagueInfo.svelte
  src/lib/components/featured_match/loaders/tablet/Placeholder_TvStations.svelte
  src/lib/components/featured_match/loaders/tablet/Placeholder_ValueBets.svelte
  src/lib/components/featured_match/loaders/tablet/Placeholder_VisualVote.svelte
  src/lib/components/header/Header.svelte
  src/lib/components/header/assets/icon-check.svg
  src/lib/firebase/index.ts
  src/lib/firebase/init.ts
  src/lib/geoJs/init.ts
  src/lib/graphql/init_graphQL.ts
  src/lib/graphql/mutation.ts
  src/lib/graphql/query.ts
  src/lib/model/content-loader-interface.ts
  src/lib/model/firebase-real-db-interface.ts
  src/lib/model/geo-js-interface.ts
  src/lib/model/interface-fixture.ts
  src/lib/model/response_models.ts
  src/lib/model/scores_header_translations.ts
  src/lib/store/lang-select.ts
  src/lib/store/user-settings.ts
  src/lib/store/vote_fixture.ts
  src/routes/[lang].svelte
  src/routes/__layout.svelte
  src/routes/index.svelte
  src/service-worker.ts
  static/assets/svg/icon/icon-close.svg
  static/assets/svg/icon/icon-equally.svg
  static/assets/svg/icon/white-close.svg
  svelte.config.js
Labels: bug, enhancement

#93 Feature/seo enhacement
  src/lib/components/featured_match/_FeaturedMatch_Widget.svelte
  src/routes/[lang].svelte
  src/routes/__layout.svelte
  src/routes/index.svelte
Labels: enhancement

#94 Feature/seo enhacement
  src/routes/index.svelte
Labels: enhancement

#96 Feature/seo enhacement
  src/lib/api/utils.ts
  src/routes/[lang].svelte
  src/routes/__layout.svelte
  src/routes/api/featured-match-seo.json.ts
  src/routes/api/header-translation.json.ts
  src/routes/index.svelte
Labels: enhancement

#103 Dev
  package.json
  src/lib/components/header/_Header.svelte
  src/lib/geoJs/init.ts
  src/routes/api/featured_match/cache-data-update.json.ts
  src/routes/api/featured_match/cache-seo-update.json.ts
Labels: bug, enhancement
