Repository Betarena/scores, pull requests merged in 2024-05, with the labels that each got.

#2092 fix script error when filter returns empty mapTags
  src/lib/components/section/authors/page/tags/content/Tags-Main.svelte
  src/lib/components/ui/wrappers/ScrollDataWrapper.svelte
Labels: 🐞 [A] bug, 🌟 [A] enhancement

#2095 Hotfix/player page/draft/0
  package-lock.json
  package.json
  src/lib/sveltekit/load/load.player.ts
  src/routes/(scores)/[[lang=lang]]/[player=player]/[...player_fill]/+page.server.ts
Labels: 🐞 [A] bug, 🚨 [A] urgent, semver:patch

#2097 fix: userguid modal (#2096)
  src/lib/components/_main_/userguide/Userguide-Competition-1-Main.svelte
  src/lib/components/_main_/userguide/Userguide-Competition-1-Widget.svelte
  src/lib/components/page/lobby/Layout.svelte
  src/lib/store/modal.ts
  src/routes/+layout.svelte
Labels: semver:patch

#2100 Dev
  package-lock.json
  package.json
  src/lib/components/_main_/userguide/Userguide-Competition-1-Main.svelte
  src/lib/components/section/authors/page/author/content/Author-Main.svelte
Labels: semver:patch

#2130 feature/authors-articles-cache-ttl
  .eslintrc.yaml
  package-lock.json
  package.json
  src/hooks.server.ts
  src/lib/components/_main_/header/Header-Nav-Btn.svelte
  src/lib/components/section/authors/page/author/Layout.svelte
  src/lib/components/section/authors/page/author/content/Author-Main.svelte
  src/lib/components/section/authors/page/author/content/Author-Widget.svelte
  src/lib/components/section/authors/page/content/ArticleCard.svelte
  src/lib/components/section/authors/page/content/ArticleLoader.svelte
  src/lib/components/section/authors/page/content/Layout.svelte
  src/lib/sveltekit/endpoint/author.article.ts
  src/lib/sveltekit/endpoint/author.tag.ts
  src/lib/sveltekit/load/load.authors.ts
  src/lib/sveltekit/load/load.tags.ts
  src/lib/utils/debug.ts
  src/lib/utils/navigation.ts
Labels: 🐞 [A] bug, 🌟 [A] enhancement

#2132 feature/authors-articles-cache-ttl (#2130)
  .eslintrc.yaml
  package-lock.json
  package.json
  src/hooks.server.ts
  src/lib/components/_main_/header/Header-Nav-Btn.svelte
  src/lib/components/section/authors/page/author/Layout.svelte
  src/lib/components/section/authors/page/author/content/Author-Main.svelte
  src/lib/components/section/authors/page/author/content/Author-Widget.svelte
  src/lib/components/section/authors/page/content/ArticleCard.svelte
  src/lib/components/section/authors/page/content/ArticleLoader.svelte
  src/lib/components/section/authors/page/content/Layout.svelte
  src/lib/sveltekit/endpoint/author.article.ts
  src/lib/sveltekit/endpoint/author.tag.ts
  src/lib/sveltekit/load/load.authors.ts
  src/lib/sveltekit/load/load.tags.ts
  src/lib/utils/debug.ts
  src/lib/utils/navigation.ts
Labels: 🌟 [A] enhancement, semver:patch

#2140 hotfix(ads): correct ads-engine data access
  src/routes/+layout.svelte
Labels: 🐞 [A] bug, 📣 [A] high priority, 🚨 [A] urgent, semver:patch

#2144 build(ad-engine): update to 0.0.51
  package-lock.json
  package.json
Labels: dependencies, semver:patch
