Repository Betarena/scores, pull requests merged in 2024-04, with the labels that each got.

#2073 Chore/restructure/draft/0
  .eslintrc.yaml
  .gitignore
  .vscode/settings.json
  .vscode/snippets.code-snippets
  .vscode/terminals.example.json
  .vscode/terminals.json
  Makefile
  src/hooks.client.ts
  src/lib/types/env.d.ts
  src/lib/types/vite.d.ts
  vite.config.ts
Labels: documentation, 🌟 [A] enhancement, 📣 [A] high priority

#2075 build: update ad-engine dependency
  package-lock.json
  package.json
Labels: 🌟 [A] enhancement, 📣 [A] high priority, semver:patch

#2077 build: update ad-engine dependency
  package-lock.json
  package.json
Labels: 🌟 [A] enhancement, 📣 [A] high priority, semver:patch

#2078 build: update ad-engine dependency
  package-lock.json
  package.json
Labels: 📣 [A] high priority, semver:patch

#2080 fix: highlights
  debug.log
  src/lib/components/page/lobby/highlights/Highlights-Grid-Row.svelte
Labels: semver:patch

#2086 fix(debug): disable use of debug log persistance (+misc)
  .github/workflows/pr-main-tag.yml
  .gitignore
  debug.log
  src/lib/utils/debug.ts
Labels: 🐞 [A] bug, semver:patch
