Repository Betarena/scores, pull requests merged in 2024-06, with the labels that each got.

#2156 Refactor/change/drfat/0
  src/lib/components/misc/modal/ModalMain.svelte
  src/lib/components/shared/BuyBta/Buy-BTA-Button.svelte
  src/lib/store/session.ts
  src/routes/+layout.svelte
Labels: 🌟 [A] enhancement

#2160 hotfix(ad-engine): correct reload
  src/routes/+layout.svelte
Labels: 🐞 [A] bug, 📣 [A] high priority, semver:patch

#2171 hotfix(articles): update content articles widget
  src/lib/components/section/authors/page/content/articles/Article-Widget.svelte
Labels: 🐞 [A] bug

#2170 dev-to-prod
  src/lib/components/_main_/header/Header-Sports-Btn.svelte
  src/lib/components/page/fixture/incidents/Incidents-Main.svelte
  src/lib/components/page/fixture/incidents/Incidents-Widget.svelte
  src/lib/components/page/home/Layout.svelte
  src/lib/components/page/home/feat-match/FeatMatch-Main.svelte
  src/lib/components/page/home/league-list/LeagueList-Main.svelte
  src/lib/components/page/home/leagues-table/Leagues-Table-Main.svelte
  src/lib/components/page/home/leagues-table/Leagues-Table-Team-Row.svelte
  src/lib/components/section/authors/page/content/articles/Article-Widget.svelte
  src/lib/components/section/authors/page/tags/content/Tags-Widget.svelte
  src/lib/utils/color_thief.ts
Labels: semver:patch

#2179 feature/fixture-content-widget/draft/0
  package-lock.json
  package.json
  src/lib/components/page/fixture/content/Content-Main.svelte
  src/lib/components/page/fixture/content/Content-Widget.svelte
  src/lib/components/page/home/livescores-v2/Livescores_Fixture_Row.svelte
  src/lib/sveltekit/endpoint/fixture.content.ts
  src/routes/api/data/fixture/content/+server.ts
Labels: 🌟 [A] enhancement

#2180 dev-to-prod
  package-lock.json
  package.json
  src/lib/components/page/fixture/content/Content-Main.svelte
  src/lib/components/page/fixture/content/Content-Widget.svelte
  src/lib/components/page/home/livescores-v2/Livescores_Fixture_Row.svelte
  src/lib/sveltekit/endpoint/fixture.content.ts
  src/routes/api/data/fixture/content/+server.ts
Labels: 🌟 [A] enhancement, semver:patch

#2195 dev-to-prod
  src/lib/components/_main_/header_redisigned/HeaderRedesigned.svelte
  src/lib/components/misc/modal/ModalMain.svelte
  src/lib/components/page/competition/Layout.svelte
  src/lib/components/page/competition/main/Main-Modal-Multiple.svelte
  src/lib/components/page/competition/main/Main-Participants-List.svelte
  src/lib/components/page/fixture/Layout.svelte
  src/lib/components/page/league/Layout.svelte
  src/lib/components/page/player/Layout.svelte
  src/lib/components/section/authors/page/content/Layout.svelte
  src/lib/store/modal.ts
  src/routes/+layout.svelte
Labels: semver:patch

#2205 dev-to-prod
  src/lib/components/page/home/feat-match/FeatMatch-Main.svelte
  src/lib/components/page/home/livescores-v2/Livescores_Main.svelte
  src/lib/utils/color_thief.ts
Labels: semver:patch

#2210 dev-to-prod
  src/lib/components/_main_/footer/FooterNavigationBlock.svelte
  src/lib/components/_main_/footer/FooterSide.svelte
  src/lib/components/page/home/feat-bet-site/FeatBetSite-Loader.svelte
  src/lib/components/page/home/feat-match/FeatMatch-Loader.svelte
  src/lib/components/page/home/leagues-table/Leagues-Table-Loader.svelte
  src/lib/components/page/home/top-goalscorers/TopGoalScorers-Loader.svelte
  src/lib/components/section/authors/page/author/content/Author-Loader.svelte
  src/lib/utils/deeplink.ts
Labels: semver:patch

#2212 dev-to-prod
  src/lib/utils/user.ts
Labels: semver:patch

#2221 Feature/manifest/draft/2 (#2220)
  src/app.html
  src/progressier.js
  src/service-worker.ts
Labels: semver:patch
