Repository Betarena/scores, pull requests merged in 2025-02, with the labels that each got.

#2328 fix/ci/draft/0
  .github/workflows/pr.main.check.yml
  .github/workflows/pr.main.open.yml
  .github/workflows/pr.main.tag.yml
Labels: 🐞 [A] bug

#2329 Fix/scope/0
  package-lock.json
  package.json
  src/lib/components/_main_/header_redisigned/HeaderNavigation.svelte
  src/lib/components/_main_/mobile-menu/MobileMenu.svelte
  src/lib/components/_main_/mobile-menu/assets/circle.svelte
  src/lib/components/page/fixture/incidents/Incidents-Row.svelte
  src/lib/components/page/fixture/standings/Standings-Main.svelte
  src/lib/components/page/home/livescores-v2/Livescores_Main.svelte
  src/lib/components/page/league/standings/_Standings_Widget.svelte
  src/lib/components/page/profile/Widget-MenuOpt-Row.svelte
  src/lib/components/page/profile/Widget-MenuOpt.svelte
  src/lib/components/page/profile/withdraw/Modal-Withdraw-Form.svelte
  src/lib/components/page/profile/withdraw/Widget-Withdraw.svelte
  src/lib/components/section/authors/common_ui/helpers.ts
  src/lib/components/section/authors/page/sportstack/SportackLayout.svelte
  src/lib/components/section/authors/page/sportstack/views/SportstackMain.svelte
  src/lib/components/section/authors/page/sportstack/views/SportstackWidget.svelte
  src/lib/components/section/authors/page/tags/content/Articels-Card.svelte
  src/lib/components/section/authors/page/user/articles/AuthorProfileMain.svelte
  src/lib/components/ui/Modal.svelte
  src/lib/components/ui/NoData.svelte
  src/lib/sveltekit/endpoint/author.profile.ts
  src/lib/sveltekit/load/load.sportstack.ts
Labels: semver:minor

#2332 fix/remove-optimonk
  src/app.html
Labels: semver:patch

#2330 fix/ci/draft/1
  .github/workflows/pr.main.tag.yml
Labels: 🐞 [A] bug

#2334 feature/buy-link
  src/lib/components/page/profile/Widget-MenuOpt.svelte
  src/lib/components/shared/BuyBta/Buy-BTA-Button.svelte
Labels: semver:patch
